version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=postgres_password
            - POSTGRES_DB=simple_blog_api
        restart: always
          
    blog-api:
      image: drajesh174/simple_blog_api
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
         - '3000:3000'
      environment:
          - POSTGRES_HOST=postgres
          - POSTGRESS_PORT=5432
          - POSTGRES_USERNAME=postgres
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_DB=simple_blog_api
